# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-19 09:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import prokat.models


class Migration(migrations.Migration):

    dependencies = [
        ('prokat', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=prokat.models.image_folder),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prokat.Type'),
        ),
    ]
