# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-27 13:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('prokat', '0007_auto_20180527_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 5, 27, 13, 5, 15, 573403, tzinfo=utc), verbose_name='Дата начала поездки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_end',
            field=models.DateField(default=datetime.datetime(2018, 5, 27, 13, 5, 15, 573403, tzinfo=utc), verbose_name='Дата конца поездки'),
        ),
    ]
