# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 10:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('prokat', '0008_auto_20180527_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stat',
            field=models.CharField(blank=True, choices=[('Принято в обработку', 'Принято в обработку'), ('Забронировано', 'Забронировано'), ('У клиента', 'У клиента'), ('Бронь отменена', 'Бронь отменена'), ('Заказ выполнен', 'Заказ выполнен')], max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 5, 30, 10, 31, 18, 627619, tzinfo=utc), verbose_name='Дата начала поездки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_end',
            field=models.DateField(default=datetime.datetime(2018, 5, 30, 10, 31, 18, 627619, tzinfo=utc), verbose_name='Дата конца поездки'),
        ),
    ]
