# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-03 10:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('prokat', '0009_auto_20180530_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2018, 6, 3, 10, 57, 31, 899435, tzinfo=utc), verbose_name='Дата начала поездки')),
                ('date_end', models.DateField(default=datetime.datetime(2018, 6, 3, 10, 57, 31, 899435, tzinfo=utc), verbose_name='Дата конца поездки')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 6, 3, 10, 57, 31, 899435, tzinfo=utc), verbose_name='Дата начала поездки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_end',
            field=models.DateField(default=datetime.datetime(2018, 6, 3, 10, 57, 31, 899435, tzinfo=utc), verbose_name='Дата конца поездки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='stat',
            field=models.CharField(blank=True, choices=[('Принято в обработку', 'Принято в обработку'), ('Забронировано', 'Забронировано'), ('У клиента', 'У клиента'), ('Бронь отменена', 'Бронь отменена'), ('Заказ выполнен', 'Заказ выполнен')], max_length=100, verbose_name='Статус'),
        ),
    ]
