# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-03 13:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('prokat', '0010_auto_20180603_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkdate',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 6, 3, 13, 46, 21, 399861, tzinfo=utc), verbose_name='Дата начала поездки'),
        ),
        migrations.AlterField(
            model_name='checkdate',
            name='date_end',
            field=models.DateField(default=datetime.datetime(2018, 6, 3, 13, 46, 21, 399861, tzinfo=utc), verbose_name='Дата конца поездки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 6, 3, 13, 46, 21, 399861, tzinfo=utc), verbose_name='Дата начала поездки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_end',
            field=models.DateField(default=datetime.datetime(2018, 6, 3, 13, 46, 21, 399861, tzinfo=utc), verbose_name='Дата конца поездки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
